In [1]:
import cv2
import numpy as np

In [11]:
image = cv2.imread("/Users/eduard.balamatiuc/sigmoid/excalibur-live/lesson12/images/mario2.jpg", cv2.IMREAD_COLOR)
# cv2.imshow("image", image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [12]:
main_arr = np.array([
    [[1, 1, 1], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]],
    [[15, 1, 1], [0, 0, 0], [15, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]], 
    [[1, 1, 1], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]], 
    [[1, 1, 1], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]], 
    [[1, 1, 1], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]], 
    [[1, 1, 1], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 0, 0]],
])

filter_arr = np.array([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
])

In [24]:
[6/9, 6/9, 6/9]

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [35]:
def compute_filter(main_arr, filter_arr):
    col_in, raw_in, cor_in = main_arr.shape
    col_fil, raw_fil = filter_arr.shape
    col_out = col_in - col_fil + 1
    raw_out = raw_in - raw_fil + 1
    cor_out = cor_in
    result = np.array([])
    for i in range(col_out):
        for j in range(raw_out):
            multiplication_result = main_arr[i:i+3, j:j+3, :] * filter_arr
            sum_result = np.sum(np.sum(multiplication_result, axis=0), axis=0)
            # print(f"This are sum results {sum_result}\n")
            result = np.append(result, sum_result)
    return result.reshape(col_out, raw_out, cor_out).astype(np.uint8)

In [36]:
print(compute_filter(main_arr, filter_arr))

[[[0 0 0]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [1 1 1]
  [0 0 0]]]


In [ ]:
filtered_image = compute_filter(image, filter_arr)

In [ ]:
cv2.imshow("filtered_image", filtered_image)
cv2.waitKey(0)
cv2.destroyAllWindows()