In [15]:
import cv2
import numpy as np

In [16]:
image = cv2.imread('images/mario.jpg', cv2.IMREAD_COLOR)

In [17]:
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
print(image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [19]:
print(type(image))

<class 'numpy.ndarray'>


In [21]:
image.size

120000

In [31]:
main_arr = np.array(
    [
        [1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1, 0]  
    ]
)

filter_arr = np.array([
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9],
    [1/9, 1/9, 1/9]
])

In [32]:
main_arr.shape

(6, 6)

In [189]:
def compute_filter(main_arr, filter_arr):
    col_in, row_in, cor_in = main_arr.shape
    col_fil, row_fil = filter_arr.shape
    col_out = col_in - col_fil + 1
    row_out = row_in - row_fil + 1
    result = np.zeros((col_out, row_out, cor_in)) 

    filter_sum = np.sum(filter_arr) if np.sum(filter_arr) != 0 else 1 

    for i in range(col_out):
        for j in range(row_out):
            for c in range(cor_in):
                multiplication_result = main_arr[i:i+3, j:j+3, c] * filter_arr
                sum_result = np.sum(multiplication_result) / 255

                result[i, j, c] = sum_result

        #print(result, '\n\n')

    return result


In [190]:
filtred_image = compute_filter(image, filter_arr)

In [191]:
col_in, row_in, cor_in = image.shape
col_fil, row_fil = filter_arr.shape

print(col_in, row_in, cor_in)
print(col_fil, row_fil)


200 200 3
3 3


In [192]:
cv2.imshow('image', filtred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()